Update Check_Merge_Conflicts_and_Create_Pull_Request .yml
adjusted indentations

diff --git a/.github/workflows/Check_Merge_Conflicts_and_Create_Pull_Request .yml b/.github/workflows/Check_Merge_Conflicts_and_Create_Pull_Request .yml
--- a/.github/workflows/Check_Merge_Conflicts_and_Create_Pull_Request .yml
+++ b/.github/workflows/Check_Merge_Conflicts_and_Create_Pull_Request .yml
@@ -80,25 +80,26 @@ jobs:
         # Script to run for the step
         run: |
           # Use the GitHub CLI to create a pull request
-          gh pr create \  
+          gh pr create \
             # Set the title of the pull request
-            --title "${{ github.ref }} -> main" \  
+            --title "${{ github.ref }} -> main" \
             # Set the commit message for the pull request
-            --body "Automated pull request creation from ${{ github.ref }} branch." \  
+            --body "Automated pull request creation from ${{ github.ref }} branch." \
             # Specify the reviewer for the pull request
-            --reviewer "dheeraj1228" \  
+            --reviewer "reviewer_username" \
             # Specify the base branch for the pull request
-            --base "main" \  
+            --base "main" \
             # Specify the head branch for the pull request
-            --head "${{ github.ref }}" \  
+            --head "${{ github.ref }}" \
             # Specify the repository where the pull request will be created
-            --repo "${{ github.repository }}"
+            --repo "${{ github.repository }}" \
             # Provide the GitHub token for authentication
             --token "${{ secrets.GH_TOKEN }}"
-            # Check if the pull request creation was successful
-            if [ $? -ne 0 ]; then
-              # Notifies the user if pull request creation failed
-              echo "::error::Failed to create pull request. Please check the workflow logs for details."
-              # Exit the script
-              exit 1
-            fi
+
+          # Check if the pull request creation was successful
+          if [ $? -ne 0 ]; then
+            # Notifies the user if pull request creation failed
+            echo "::error::Failed to create pull request. Please check the workflow logs for details."
+            # Exit the script
+            exit 1
+          fi
